### ISSUE TITLE
plugins are hard-codeded.  The manager should scan a folder

### ISSUE THREAD

**Issue by horner** [ArshSSandhu/Nodejs-cli-plugin-system#13]
This code is in the wrong place:

https://github.com/ArshSSandhu/Nodejs-cli-plugin-system/blob/2311d2a1bd03c81353df7f9df81d3b48d8a547d8/src/textCLI.ts#L19

Determination of which plug-ins to load should be in the application layer, not in the library layer:

For example, 
https://github.com/ArshSSandhu/Nodejs-cli-plugin-system/blob/2311d2a1bd03c81353df7f9df81d3b48d8a547d8/src/index.ts#L4

You should scan the plugin folder and find the ts files and make the structure from disk

**Comment by ArshSSandhu** [comment]
This issue has been resolved! Thanks
